### ISSUE TITLE
Sample not working --- Windows Server 2012, Node V7.4.0, VS2015, Python 2.7.x

### ISSUE THREAD

**Issue by stevyrino** [xdenser/node-fb-sample#6]
C:\>cd projectfbsample

C:\ProjectFBSample>npm install

> firebird@0.0.15 install C:\ProjectFBSample\node_modules\firebird
> node-gyp rebuild

C:\ProjectFBSample\node_modules\firebird>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fb-bindings.cc
  fb-bindings-blob.cc
  fb-bindings-fbresult.cc
  fb-bindings-connection.cc
  fb-bindings-eventblock.cc
  fb-bindings-fbeventemitter.cc
  fb-bindings-statement.cc
  win_delay_load_hook.cc
     Creating library C:\ProjectFBSample\node_modules\firebird\build\Release\binding.lib and object C:\ProjectFBSample\node_modules
  \firebird\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> C:\ProjectFBSample\node_modules\firebird\build\Release\\binding.node
  binding.vcxproj -> C:\ProjectFBSample\node_modules\firebird\build\Release\binding.pdb (Full PDB)
node-fb-sample@0.0.2 C:\ProjectFBSample
+-- body-parser@1.16.0
| +-- bytes@2.4.0
| +-- content-type@1.0.2
| +-- debug@2.6.0
| | `-- ms@0.7.2
| +-- depd@1.1.0
| +-- http-errors@1.5.1
| | +-- inherits@2.0.3
| | +-- setprototypeof@1.0.2
| | `-- statuses@1.3.1
| +-- iconv-lite@0.4.15
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- qs@6.2.1
| +-- raw-body@2.2.0
| | `-- unpipe@1.0.0
| `-- type-is@1.6.14
|   +-- media-typer@0.3.0
|   `-- mime-types@2.1.14
|     `-- mime-db@1.26.0
+-- express@4.14.0
| +-- accepts@1.3.3
| | `-- negotiator@0.6.1
| +-- array-flatten@1.1.1
| +-- content-disposition@0.5.1
| +-- cookie@0.3.1
| +-- cookie-signature@1.0.6
| +-- debug@2.2.0
| | `-- ms@0.7.1
| +-- encodeurl@1.0.1
| +-- escape-html@1.0.3
| +-- etag@1.7.0
| +-- finalhandler@0.5.0
| | `-- debug@2.2.0
| |   `-- ms@0.7.1
| +-- fresh@0.3.0
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- parseurl@1.3.1
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@1.1.3
| | +-- forwarded@0.1.0
| | `-- ipaddr.js@1.2.0
| +-- qs@6.2.0
| +-- range-parser@1.2.0
| +-- send@0.14.1
| | +-- debug@2.2.0
| | +-- destroy@1.0.4
| | +-- mime@1.3.4
| | `-- ms@0.7.1
| +-- serve-static@1.11.1
| +-- utils-merge@1.0.0
| `-- vary@1.1.0
`-- firebird@0.0.15
  `-- nan@2.5.0

npm WARN node-fb-sample@0.0.2 No license field.

C:\ProjectFBSample>node server
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\ProjectFBSample\node_modules\firebird\build\Release\binding.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\ProjectFBSample\node_modules\firebird\firebird.js:1:77)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

C:\ProjectFBSample>

C:\ProjectFBSample>

**Comment by xdenser** [comment]
Strange. According to build log the file "C:\ProjectFBSample\node_modules\firebird\build\Release\binding.node"
was created. Is it there ?

**Comment by xdenser** [comment]
I know what is the problem. Copy FBClient.dll to C:\ProjectFBSample\node_modules\firebird\build\Release\

**Comment by mendesf** [comment]
Same problem here.

C:\Users\Felipe\Desktop\repos\node-fb-sample>npm install

> firebird@0.1.2 install C:\Users\Felipe\Desktop\repos\node-fb-sample\node_modules\firebird
> node-gyp rebuild


C:\Users\Felipe\Desktop\repos\node-fb-sample\node_modules\firebird>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fb-bindings.cc
  fb-bindings-blob.cc
  fb-bindings-fbresult.cc
  fb-bindings-connection.cc
  fb-bindings-eventblock.cc
  fb-bindings-fbeventemitter.cc
  fb-bindings-statement.cc
  fb-bindings-transaction.cc
  win_delay_load_hook.cc
     Creating library C:\Users\Felipe\Desktop\repos\node-fb-sample\node_modules\firebird\build\Release\binding.lib and object C:\Users\Felipe\Desktop\repos\node-fb-sample\node_modules\firebird\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> C:\Users\Felipe\Desktop\repos\node-fb-sample\node_modules\firebird\build\Release\\binding.node
  binding.vcxproj -> C:\Users\Felipe\Desktop\repos\node-fb-sample\node_modules\firebird\build\Release\binding.pdb (Full PDB)
node-fb-sample@0.0.2 C:\Users\Felipe\Desktop\repos\node-fb-sample
+-- body-parser@1.18.2
| +-- bytes@3.0.0
| +-- content-type@1.0.4
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- depd@1.1.2
| +-- http-errors@1.6.2
| | +-- depd@1.1.1
| | +-- inherits@2.0.3
| | +-- setprototypeof@1.0.3
| | `-- statuses@1.4.0
| +-- iconv-lite@0.4.19
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- qs@6.5.1
| +-- raw-body@2.3.2
| | `-- unpipe@1.0.0
| `-- type-is@1.6.15
|   +-- media-typer@0.3.0
|   `-- mime-types@2.1.17
|     `-- mime-db@1.30.0
+-- express@4.16.2
| +-- accepts@1.3.4
| | `-- negotiator@0.6.1
| +-- array-flatten@1.1.1
| +-- content-disposition@0.5.2
| +-- cookie@0.3.1
| +-- cookie-signature@1.0.6
| +-- encodeurl@1.0.1
| +-- escape-html@1.0.3
| +-- etag@1.8.1
| +-- finalhandler@1.1.0
| | `-- statuses@1.3.1
| +-- fresh@0.5.2
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- parseurl@1.3.2
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@2.0.2
| | +-- forwarded@0.1.2
| | `-- ipaddr.js@1.5.2
| +-- range-parser@1.2.0
| +-- safe-buffer@5.1.1
| +-- send@0.16.1
| | +-- destroy@1.0.4
| | +-- mime@1.4.1
| | `-- statuses@1.3.1
| +-- serve-static@1.13.1
| +-- setprototypeof@1.1.0
| +-- statuses@1.3.1
| +-- utils-merge@1.0.1
| `-- vary@1.1.2
`-- firebird@0.1.2
  `-- nan@2.8.0

npm WARN node-fb-sample@0.0.2 No license field.

C:\Users\Felipe\Desktop\repos\node-fb-sample>

I tried copied and pasted the fbclient.dll as you said, but I've got another error:

C:\Users\Felipe\Desktop\repos\node-fb-sample>node server.js
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 não é um aplicativo Win32 válido.
\\?\C:\Users\Felipe\Desktop\repos\node-fb-sample\node_modules\firebird\build\Release\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Felipe\Desktop\repos\node-fb-sample\node_modules\firebird\firebird.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

C:\Users\Felipe\Desktop\repos\node-fb-sample>

**Comment by xdenser** [comment]
NodeJS and DLL target architecture should be the same. I.e. if you are using 64bit nodejs, you should use 64bit  fbclient.dll . Same for 32 bit.

**Comment by mendesf** [comment]
@xdenser sorry, my bad.
